### ISSUE TITLE
Changing time zone on Pi causes decoding-carelink to fail reading clock

### ISSUE THREAD

**Issue by amazaheri** [bewest/decoding-carelink#158]
oref0-monitor/clock.json raised bytearray index out of range
Traceback (most recent call last):
File "/usr/local/bin/openaps-report", line 4, in <module>
import('pkg_resources').run_script('openaps==0.0.8', 'openaps-report')
File "build/bdist.linux-armv7l/egg/pkgresources/_init.py", line 735, in run_script
File "build/bdist.linux-armv7l/egg/pkgresources/_init.py", line 1652, in run_script
File "/usr/local/lib/python2.7/dist-packages/openaps-0.0.8-py2.7.egg/EGG-INFO/scripts/openaps-report";, line 82, in <module>
app( )
File "/usr/local/lib/python2.7/dist-packages/openaps-0.0.8-py2.7.egg/openaps/cli/init.py", line 44, in call
self.run(self.args)
File "/usr/local/lib/python2.7/dist-packages/openaps-0.0.8-py2.7.egg/EGG-INFO/scripts/openaps-report";, line 75, in run
output = app(args, self)
File "/usr/local/lib/python2.7/dist-packages/openaps-0.0.8-py2.7.egg/openaps/cli/subcommand.py";, line 50, in call
return self.method.main(args, app)
File "/usr/local/lib/python2.7/dist-packages/openaps-0.0.8-py2.7.egg/openaps/reports/invoke.py";, line 40, in main
output = task.method(args, app)
File "/usr/local/lib/python2.7/dist-packages/openaps-0.0.8-py2.7.egg/openaps/uses/use.py";, line 45, in call
output = self.main(args, app)
File "/usr/local/lib/python2.7/dist-packages/openaps-0.0.8-py2.7.egg/openaps/vendors/medtronic.py";, line 207, in main
return self.pump.model.read_clock( )
File "/usr/local/lib/python2.7/dist-packages/decocare-0.0.19-py2.7.egg/decocare/models/init.py", line 25, in call
self.response = inst.session.query(self.msg, **kwds)
File "/usr/local/lib/python2.7/dist-packages/decocare-0.0.19-py2.7.egg/decocare/session.py";, line 101, in query
self.execute(command)
File "/usr/local/lib/python2.7/dist-packages/decocare-0.0.19-py2.7.egg/decocare/session.py";, line 98, in execute
return super(type(self), self).execute(command)
File "/usr/local/lib/python2.7/dist-packages/decocare-0.0.19-py2.7.egg/decocare/session.py";, line 39, in execute
self.download( )
File "/usr/local/lib/python2.7/dist-packages/decocare-0.0.19-py2.7.egg/decocare/session.py";, line 54, in download
self.command.respond(data)
File "/usr/local/lib/python2.7/dist-packages/decocare-0.0.19-py2.7.egg/decocare/commands.py";, line 58, in respond
self.getData( )
File "/usr/local/lib/python2.7/dist-packages/decocare-0.0.19-py2.7.egg/decocare/commands.py";, line 635, in getData
'hour' : int(data[0]),
IndexError: bytearray index out of range

**Comment by scottleibrand** [comment]
Is your pump.ini expires time now in the future? If so, delete that line to force it to re-init the pump. 

-Scott




On Tue, Dec 29, 2015 at 9:11 PM -0800, "Ali Mazaheri" <notifications@github.com> wrote:












oref0-monitor/clockjson raised bytearray index out of range

Traceback (most recent call last):

File "/usr/local/bin/openaps-report", line 4, in 

import('pkg_resources')run_script('openaps==008', 'openaps-report')

File "build/bdistlinux-armv7l/egg/pkgresources/_initpy", line 735, in run_script

File "build/bdistlinux-armv7l/egg/pkgresources/_initpy", line 1652, in run_script

File "/usr/local/lib/python27/dist-packages/openaps-008-py27egg/EGG-INFO/scripts/openaps-report";, line 82, in 

app( )

File "/usr/local/lib/python27/dist-packages/openaps-008-py27egg/openaps/cli/initpy", line 44, in call

selfrun(selfargs)

File "/usr/local/lib/python27/dist-packages/openaps-008-py27egg/EGG-INFO/scripts/openaps-report";, line 75, in run

output = app(args, self)

File "/usr/local/lib/python27/dist-packages/openaps-008-py27egg/openaps/cli/subcommandpy";, line 50, in call

return selfmethodmain(args, app)

File "/usr/local/lib/python27/dist-packages/openaps-008-py27egg/openaps/reports/invokepy";, line 40, in main

output = taskmethod(args, app)

File "/usr/local/lib/python27/dist-packages/openaps-008-py27egg/openaps/uses/usepy";, line 45, in call

output = selfmain(args, app)

File "/usr/local/lib/python27/dist-packages/openaps-008-py27egg/openaps/vendors/medtronicpy";, line 207, in main

return selfpumpmodelread_clock( )

File "/usr/local/lib/python27/dist-packages/decocare-0019-py27egg/decocare/models/initpy", line 25, in call

selfresponse = instsessionquery(selfmsg, **kwds)

File "/usr/local/lib/python27/dist-packages/decocare-0019-py27egg/decocare/sessionpy";, line 101, in query

selfexecute(command)

File "/usr/local/lib/python27/dist-packages/decocare-0019-py27egg/decocare/sessionpy";, line 98, in execute

return super(type(self), self)execute(command)

File "/usr/local/lib/python27/dist-packages/decocare-0019-py27egg/decocare/sessionpy";, line 39, in execute

selfdownload( )

File "/usr/local/lib/python27/dist-packages/decocare-0019-py27egg/decocare/sessionpy";, line 54, in download

selfcommandrespond(data)

File "/usr/local/lib/python27/dist-packages/decocare-0019-py27egg/decocare/commandspy";, line 58, in respond

selfgetData( )

File "/usr/local/lib/python27/dist-packages/decocare-0019-py27egg/decocare/commandspy";, line 635, in getData

'hour' : int(data[0]),

IndexError: bytearray index out of range
