### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'write' with mm-latest.py 

### ISSUE THREAD

**Issue by PieterGit** [bewest/decoding-carelink#168]
I get a traceback with the following command:
$ mm-latest.py --serial 123456  > mm-file.txt

Traceback (most recent call last):
  File "/usr/local/bin/mm-latest.py", line 4, in <module>
    **import**('pkg_resources').run_script('decocare==0.0.21', 'mm-latest.py')
  File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 726, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 1651, in run_script
  File "/usr/local/lib/python2.7/dist-packages/decocare-0.0.21-py2.7.egg/EGG-INFO/scripts/mm-latest.py", line 211, in <module>
    app.run(None)
  File "/usr/local/lib/python2.7/dist-packages/decocare-0.0.21-py2.7.egg/decocare/helpers/cli.py", line 114, in run
    self.main(args)
  File "/usr/local/lib/python2.7/dist-packages/decocare-0.0.21-py2.7.egg/EGG-INFO/scripts/mm-latest.py", line 200, in main
    self.report_status(args)
  File "/usr/local/lib/python2.7/dist-packages/decocare-0.0.21-py2.7.egg/EGG-INFO/scripts/mm-latest.py", line 130, in report_status
    args.status.write(json.dumps(self.status, indent=2))
AttributeError: 'bool' object has no attribute 'write' 

I have a EU Paradigm 754.
Is this a decocare issue?
If you want more information, please let me know.
##

**Comment by PieterGit** [comment]
Closing after 10 years. 754 is not in use any more
