### ISSUE TITLE
Parsing history fails (mm-latest)

### ISSUE THREAD

**Issue by ktomy** [bewest/decoding-carelink#56]
python mm-latest.py  --port /dev/ttyUSB0 --serial 639191 --init

## do stuff with an insulin pump over RF
using ` Namespace(basal=True, clock=True, dryrun=False, init=True, minutes=30, no_postlude=False, no_prelude=False, no_rf_prelude=False, parsed_data=<open file '<stdout>', mode 'w' at 0xb6d2f078>, port='/dev/ttyUSB0', reservoir=True, serial='639191', status=True, temp=True, verbose=None) `
```
```
```
```
```
```
```
```
```javascript
{'radio': {'errors.crc': 0,
           'errors.naks': 0,
           'errors.sequence': 0,
           'errors.timeouts': 0,
           'packets.received': 274L,
           'packets.transmit': 282L},
 'usb': {'errors.crc': 0,
         'errors.naks': 0,
         'errors.sequence': 0,
         'errors.timeouts': 1,
         'packets.received': 675L,
         'packets.transmit': 675L}}
```
```
PowerControl SERIAL 639191
```
### PUMP MODEL: `ReadPumpModel:size[64]:data:'715'`
response: ReadSettings:size[64]:data:{'low_reservoir_warn_point': 48, 'keypad_lock_status': 1, 'maxBasal': 1, 'temp_basal': {'percent': 100, 'type': 'Units/hour'}, 'paradigm_enabled': 0, 'insulinConcentration': 100, 'audio_bolus_enable': False, 'variable_bolus_enable': True, 'alarm': {'volume': 1, 'mode': 2}, 'rf_enable': False, 'block_enable': False, 'timeformat': 1, 'auto_off_duration_hrs': 0, 'audio_bolus_size': 0, 'selected_pattern': 0, 'patterns_enabled': False, 'insulin_action_type': 2, 'maxBolus': 2.0, 'low_reservoir_warn_type': 1}
hexdump:
```python
0000   0x00 0x01 0x00 0x01 0x01 0x14 0x00 0x28    .......(
0008   0x01 0x00 0x00 0x00 0x00 0x00 0x00 0x64    .......d
0010   0x00 0x02 0x01 0x30 0x01 0x00 0x00 0x00    ...0....
0018   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0020   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0028   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0030   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0038   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
```
#### decoded:
```python
{'low_reservoir_warn_point': 48, 'keypad_lock_status': 1, 'maxBasal': 1, 'temp_basal': {'percent': 100, 'type': 'Units/hour'}, 'paradigm_enabled': 0, 'insulinConcentration': 100, 'audio_bolus_enable': False, 'variable_bolus_enable': True, 'alarm': {'volume': 1, 'mode': 2}, 'rf_enable': False, 'block_enable': False, 'timeformat': 1, 'auto_off_duration_hrs': 0, 'audio_bolus_size': 0, 'selected_pattern': 0, 'patterns_enabled': False, 'insulin_action_type': 2, 'maxBolus': 2.0, 'low_reservoir_warn_type': 1}
```
response: ReadRTC:size[64]:data:'2014-12-7T5:32:55'
hexdump:
```python
0000   0x05 0x20 0x37 0x07 0xde 0x0c 0x07 0x00    . 7.....
0008   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0010   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0018   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0020   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0028   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0030   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0038   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
```
#### decoded:
```python
'2014-12-7T5:32:55'
```
response: ReadPumpStatus:size[64]:data:{'status': 'normal', 'bolusing': False, 'suspended': False}
hexdump:
```python
0000   0x03 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0008   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0010   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0018   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0020   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0028   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0030   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0038   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
```
#### decoded:
```python
{'status': 'normal', 'bolusing': False, 'suspended': False}
```
response: ReadBasalTemp:size[64]:data:{'duration': 94, 'rate': 0.0}
hexdump:
```python
0000   0x00 0x00 0x00 0x00 0x00 0x5e 0x00 0x00    .....^..
0008   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0010   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0018   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0020   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0028   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0030   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0038   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
```
#### decoded:
```python
{'duration': 94, 'rate': 0.0}
```
response: ReadProfile_STD512:size[64]:data:[{'start': '00:00:00', 'rate': 0.30000000000000004}, {'start': '02:00:00', 'rate': 0.15000000000000002}, {'start': '08:00:00', 'rate': 0.15000000000000002}, {'start': '09:00:00', 'rate': 0.25}, {'start': '10:00:00', 'rate': 0.2}, {'start': '11:00:00', 'rate': 0.15000000000000002}, {'start': '13:00:00', 'rate': 0.15000000000000002}, {'start': '14:00:00', 'rate': 0.25}, {'start': '15:00:00', 'rate': 0.25}, {'start': '16:00:00', 'rate': 0.30000000000000004}, {'start': '17:00:00', 'rate': 0.30000000000000004}, {'start': '20:00:00', 'rate': 0.2}, {'start': '22:00:00', 'rate': 0.30000000000000004}, {'start': '23:00:00', 'rate': 1.0}]
hexdump:
```python
0000   0x0c 0x00 0x00 0x06 0x00 0x04 0x06 0x00    ........
0008   0x10 0x0a 0x00 0x12 0x08 0x00 0x14 0x06    ........
0010   0x00 0x16 0x06 0x00 0x1a 0x0a 0x00 0x1c    ........
0018   0x0a 0x00 0x1e 0x0c 0x00 0x20 0x0c 0x00    ..... ..
0020   0x22 0x08 0x00 0x28 0x0c 0x00 0x2c 0x28    "..(..,(
0028   0x00 0x2e 0x00 0x00 0x00 0x00 0x00 0x00    ........
0030   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0038   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
```
#### decoded:
```python
[{'start': '00:00:00', 'rate': 0.30000000000000004}, {'start': '02:00:00', 'rate': 0.15000000000000002}, {'start': '08:00:00', 'rate': 0.15000000000000002}, {'start': '09:00:00', 'rate': 0.25}, {'start': '10:00:00', 'rate': 0.2}, {'start': '11:00:00', 'rate': 0.15000000000000002}, {'start': '13:00:00', 'rate': 0.15000000000000002}, {'start': '14:00:00', 'rate': 0.25}, {'start': '15:00:00', 'rate': 0.25}, {'start': '16:00:00', 'rate': 0.30000000000000004}, {'start': '17:00:00', 'rate': 0.30000000000000004}, {'start': '20:00:00', 'rate': 0.2}, {'start': '22:00:00', 'rate': 0.30000000000000004}, {'start': '23:00:00', 'rate': 1.0}]
```
response: ReadRemainingInsulin:size[64]:data:37.0
hexdump:
```python
0000   0x01 0x72 0x00 0x00 0x00 0x00 0x00 0x00    .r......
0008   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0010   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0018   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0020   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0028   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0030   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0038   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
```
#### decoded:
```python
37.0
```
find records since 2014-12-07T05:02:55
WARNING:decocare.stick:bad zero CRC?
WARNING:decocare.stick:bad zero CRC?
WARNING:decocare.stick:bad zero CRC?
response: ReadHistoryData:size[1024]:[page][0]:data[1024]:
hexdump:
```python
0000   0x08 0x0e 0xd1 0x05 0x16 0x06 0x0e 0x00    ........
0008   0x0c 0x00 0x04 0x06 0x00 0x10 0x06 0x00    ........
0010   0x12 0x0c 0x00 0x14 0x0a 0x00 0x16 0x06    ........
0018   0x00 0x1a 0x06 0x00 0x1c 0x0c 0x00 0x1e    ........
0020   0x0c 0x00 0x20 0x0e 0x00 0x22 0x0e 0x00    .. .."..
0028   0x28 0x0a 0x00 0x2c 0x0c 0x00 0x2e 0x28    (..,...(
0030   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0038   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0040   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0048   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0050   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0058   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0060   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0068   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0070   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0078   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0080   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0088   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0090   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0098   0x09 0x0e 0xd1 0x05 0x16 0x06 0x0e 0x00    ........
00A0   0x0c 0x00 0x04 0x06 0x00 0x10 0x06 0x00    ........
00A8   0x12 0x0a 0x00 0x14 0x08 0x00 0x16 0x06    ........
00B0   0x00 0x1a 0x06 0x00 0x1c 0x0a 0x00 0x1e    ........
00B8   0x0a 0x00 0x20 0x0c 0x00 0x22 0x0c 0x00    .. .."..
00C0   0x28 0x08 0x00 0x2c 0x0c 0x00 0x2e 0x28    (..,...(
00C8   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
00D0   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
00D8   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
00E0   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
00E8   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
00F0   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
00F8   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0100   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0108   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0110   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0118   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0120   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0128   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0130   0x5b 0x00 0xf3 0x0d 0x16 0x06 0x0e 0x19    [.......
0138   0x90 0x23 0x96 0x38 0x00 0x07 0x00 0x00    .#.8....
0140   0x00 0x00 0x07 0x42 0x5c 0x08 0x14 0xb2    ...B\...
0148   0x80 0x14 0x7a 0x90 0x01 0x07 0x07 0x00    ..z.....
0150   0xf3 0x0d 0x56 0x06 0x0e 0x33 0x04 0xe6    ..V..3..
0158   0x08 0x17 0x06 0x0e 0x00 0x16 0x02 0xe6    ........
0160   0x08 0x17 0x06 0x0e 0x1e 0x00 0xca 0x2c    .......,
0168   0x17 0x06 0x0e 0x07 0x00 0x00 0x01 0x3a    .......:
0170   0xc6 0x0e 0x6c 0xc6 0x0e 0x06 0x00 0x32    ..l....2
0178   0x32 0x32 0x01 0x00 0x00 0x01 0x3a 0x00    22....:.
0180   0xae 0x37 0x00 0x8c 0x2d 0x00 0x73 0x00    .7..-.s.
0188   0x8c 0x2d 0x00 0x74 0x53 0x00 0x00 0x00    .-.tS...
0190   0x00 0x18 0x11 0x06 0x04 0x00 0x00 0x02    ........
0198   0x1f 0x00 0xe9 0x07 0x00 0x07 0x0e 0x33    .......3
01A0   0x00 0xf9 0x07 0x00 0x07 0x0e 0x00 0x16    ........
01A8   0x00 0xf9 0x07 0x00 0x07 0x0e 0x01 0x03    ........
01B0   0x03 0x00 0xc9 0x1a 0x42 0x07 0x0e 0x33    ....B..3
01B8   0x00 0xf3 0x05 0x05 0x07 0x0e 0x00 0x16    ........
01C0   0x04 0xf3 0x05 0x05 0x07 0x0e 0x00 0x00    ........
01C8   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
01D0   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
01D8   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
01E0   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
01E8   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
01F0   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
01F8   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0200   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0208   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0210   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0218   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0220   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0228   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0230   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0238   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0240   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0248   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0250   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0258   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0260   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0268   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0270   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0278   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0280   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0288   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0290   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0298   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
02A0   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
02A8   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
02B0   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
02B8   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
02C0   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
02C8   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
02D0   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
02D8   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
02E0   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
02E8   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
02F0   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
02F8   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0300   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0308   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0310   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0318   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0320   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0328   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0330   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0338   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0340   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0348   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0350   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0358   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0360   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0368   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0370   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0378   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0380   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0388   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0390   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0398   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
03A0   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
03A8   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
03B0   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
03B8   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
03C0   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
03C8   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
03D0   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
03D8   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
03E0   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
03E8   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
03F0   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
03F8   0x00 0x00 0x00 0x00 0x00 0x00 0x8e 0x9d    ........
```
#### decoded:
```python
'0000   0x08 0x0e 0xd1 0x05 0x16 0x06 0x0e 0x00    ........\n0008   0x0c 0x00 0x04 0x06 0x00 0x10 0x06 0x00    ........\n0010   0x12 0x0c 0x00 0x14 0x0a 0x00 0x16 0x06    ........\n0018   0x00 0x1a 0x06 0x00 0x1c 0x0c 0x00 0x1e    ........\n0020   0x0c 0x00 0x20 0x0e 0x00 0x22 0x0e 0x00    .. .."..\n0028   0x28 0x0a 0x00 0x2c 0x0c 0x00 0x2e 0x28    (..,...(\n0030   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0038   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0040   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0048   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0050   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0058   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0060   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0068   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0070   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0078   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0080   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0088   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0090   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0098   0x09 0x0e 0xd1 0x05 0x16 0x06 0x0e 0x00    ........\n00A0   0x0c 0x00 0x04 0x06 0x00 0x10 0x06 0x00    ........\n00A8   0x12 0x0a 0x00 0x14 0x08 0x00 0x16 0x06    ........\n00B0   0x00 0x1a 0x06 0x00 0x1c 0x0a 0x00 0x1e    ........\n00B8   0x0a 0x00 0x20 0x0c 0x00 0x22 0x0c 0x00    .. .."..\n00C0   0x28 0x08 0x00 0x2c 0x0c 0x00 0x2e 0x28    (..,...(\n00C8   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n00D0   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n00D8   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n00E0   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n00E8   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n00F0   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n00F8   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0100   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0108   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0110   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0118   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0120   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0128   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0130   0x5b 0x00 0xf3 0x0d 0x16 0x06 0x0e 0x19    [.......\n0138   0x90 0x23 0x96 0x38 0x00 0x07 0x00 0x00    .#.8....\n0140   0x00 0x00 0x07 0x42 0x5c 0x08 0x14 0xb2    ...B\\...\n0148   0x80 0x14 0x7a 0x90 0x01 0x07 0x07 0x00    ..z.....\n0150   0xf3 0x0d 0x56 0x06 0x0e 0x33 0x04 0xe6    ..V..3..\n0158   0x08 0x17 0x06 0x0e 0x00 0x16 0x02 0xe6    ........\n0160   0x08 0x17 0x06 0x0e 0x1e 0x00 0xca 0x2c    .......,\n0168   0x17 0x06 0x0e 0x07 0x00 0x00 0x01 0x3a    .......:\n0170   0xc6 0x0e 0x6c 0xc6 0x0e 0x06 0x00 0x32    ..l....2\n0178   0x32 0x32 0x01 0x00 0x00 0x01 0x3a 0x00    22....:.\n0180   0xae 0x37 0x00 0x8c 0x2d 0x00 0x73 0x00    .7..-.s.\n0188   0x8c 0x2d 0x00 0x74 0x53 0x00 0x00 0x00    .-.tS...\n0190   0x00 0x18 0x11 0x06 0x04 0x00 0x00 0x02    ........\n0198   0x1f 0x00 0xe9 0x07 0x00 0x07 0x0e 0x33    .......3\n01A0   0x00 0xf9 0x07 0x00 0x07 0x0e 0x00 0x16    ........\n01A8   0x00 0xf9 0x07 0x00 0x07 0x0e 0x01 0x03    ........\n01B0   0x03 0x00 0xc9 0x1a 0x42 0x07 0x0e 0x33    ....B..3\n01B8   0x00 0xf3 0x05 0x05 0x07 0x0e 0x00 0x16    ........\n01C0   0x04 0xf3 0x05 0x05 0x07 0x0e 0x00 0x00    ........\n01C8   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n01D0   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n01D8   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n01E0   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n01E8   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n01F0   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n01F8   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0200   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0208   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0210   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0218   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0220   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0228   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0230   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0238   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0240   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0248   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0250   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0258   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0260   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0268   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0270   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0278   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0280   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0288   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0290   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0298   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n02A0   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n02A8   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n02B0   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n02B8   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n02C0   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n02C8   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n02D0   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n02D8   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n02E0   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n02E8   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n02F0   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n02F8   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0300   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0308   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0310   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0318   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0320   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0328   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0330   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0338   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0340   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0348   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0350   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0358   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0360   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0368   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0370   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0378   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0380   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0388   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0390   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n0398   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n03A0   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n03A8   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n03B0   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n03B8   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n03C0   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n03C8   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n03D0   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n03D8   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n03E0   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n03E8   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n03F0   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........\n03F8   0x00 0x00 0x00 0x00 0x00 0x00 0x8e 0x9d    ........'
```
SINCE 2014-12-07T05:02:55

Traceback (most recent call last):
  File "mm-latest.py", line 162, in <module>
    app.run(None)
  File "/home/pi/decoding-carelink/decocare/helpers/cli.py", line 104, in run
    self.main(args)
  File "mm-latest.py", line 158, in main
    self.download_history(args)
  File "mm-latest.py", line 129, in download_history
    remainder = self.find_records(history.data)
  File "mm-latest.py", line 111, in find_records
    record = parse_record( stream, B, larger=larger )
  File "/home/pi/decoding-carelink/decocare/history.py", line 357, in parse_record
    record.parse( head + date + body )
  File "/home/pi/decoding-carelink/decocare/records/base.py", line 64, in parse
    return self.decode( )
  File "/home/pi/decoding-carelink/decocare/history.py", line 96, in decode
    (offset, rate, q) = self.body[start:end]
ValueError: need more than 2 values to unpack

**Comment by bewest** [comment]
Closing this for now, but please re-open if anyone still experiences issues.

This was happening because the page "cleaner" routine I use to strip out unwanted null padding at the end of the file was overly aggressive.  In the Basal records, it's perfectly valid to have records with nulls on the end, and the "cleaner" was eating them which caused this error.  In the short term, I try to append some nulls to the end, but the thing probably still needs some more work.  In the sheer optimism that the hack fixes the issue, closing in the short term, and hopeful will complain vociferously if anything is wrong.
